---
title: "ESM204_a2"
author: "Richard Viebrock"
date: "4/19/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE, ncols = 2}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}

# Attach necessary packaegs

library(tidyverse)
library(ggplot2)
library(wesanderson)
library(janitor)
library(broom)
library(nlstools)

```

```{r}

# Read in data

raw_data <- read_csv("HW2_Data.csv") %>% 
  clean_names()

```

```{r}

# Check relationship between data
# Linear appears appropriate for a & b

 raw_data_02 <- raw_data %>% 
   pivot_longer("mc_a":"mc_d", 
               names_to = "sector", 
                 values_to = "mc")
 
 ggplot(data = raw_data_02, aes(sample = mc))+
  geom_qq()+
   geom_qq_line()+
   facet_wrap(~sector)

# Plot estimated marginal abatement costs

 ggplot(data = raw_data_02, aes(x = abatement, y = mc))+
   geom_line()+
   geom_point()+
   stat_smooth(method = "lm",
               se = FALSE,
               formula=y ~ poly(x, 2, raw=TRUE))+
   facet_wrap(~sector,
             scale = "free")

 ggplot(data = raw_data_02, aes(x = abatement, y = mc))+
   geom_line()+
   geom_point()+
   geom_smooth(method = "lm",
               se = FALSE)+
   facet_wrap(~sector,
              scale = "free")

```

```{r}

# Get only up to 14 hours & ln transform pop
df_exp <- raw_data %>% 
  filter(mc_b > 0) %>% 
  mutate(ln_pop = log(mc_b))
  
# Model linear to get *k* estimate:
lm_k <- lm(ln_pop ~ abatement, data = df_exp)
summary(lm_k)

# Create function to estimate abatement costs

a_lm <- lm(mc_a ~ abatement, data = raw_data)
b_lm <- lm(mc_b ~ abatement, data = raw_data)
summary(b_lm)
b_nls <- nls(mc_b ~ K/(1 + A*exp(-r*abatement)),
             data = raw_data,
             start = list(K = 60,
                          A = 50,
                          r = 0.39),
             trace = TRUE)

model_out <- broom::tidy(b_nls)
summary(b_nls)

A_est <- tidy(df_nls)$estimate[1]

b_lm <- lm(mc_b ~ poly(abatement, 2, raw = TRUE), data = raw_data)
c_lm <- lm(mc_c ~ poly(abatement, 2, raw = TRUE), data = raw_data)
d_lm <- lm(mc_d ~ poly(abatement, 2, raw = TRUE), data = raw_data)
summary(a_lm)

# b_lm <- lm(mc_b ~ abatement, data = raw_data)
# c_lm <- lm(mc_c ~ abatement, data = raw_data)
# d_lm <- lm(mc_d ~ abatement, data = raw_data)

# Naming Things
y_a <- a_lm$coefficients[1]
y_1 <- a_lm$coefficients[2]

# d_lm <- lm(mc_d ~ poly(abatement, 3, raw = TRUE), data = raw_data)
# c_lm <- lm(mc_c ~ poly(abatement, 2, raw = TRUE), data = raw_data)
# b_lm <- lm(mc_b ~ poly(abatement, 2, raw = TRUE), data = raw_data)

# plot(c_lm)
```

```{r}

# Create functions using lm()'s
a_eq <- function(x) {y = y_a + y_1*(x)}
b_eq <- function(x) {y = (58.18640)/(1+10.56466*exp(-0.04849*x))}
test_b_eq <- b_eq(100)

b_eq <- function(x) {y = 8.78529 + 0.39178*(x)}
c_eq <- function(x) {y = 0.321580*(x) + 0.005390*(x^2) - 7.941422}
d_eq <- function(x) {y = 2.098529 - 0.059765*x + 0.004088*x^2}
z <- 0:150

# b_eq <- function(x) {y = -2.008211 + 0.854358*(x) + -0.003084*(x)^2}

# c_eq <- function(x) {y = 1.563e-02*x^2 -2.735e-01*x - 4.553e-05*x^3 - 1.726e+00}
# c_eq <- function(x) {y = 1.13009*x - 26.80662}
# d_eq <- function(x) {y = 0.55347*x - 12.21029}
# test <- c_eq_demand(100)

a_eq_demand <- function(q) {y = 1.663 + 0.513*(170) - 0.513*(q)}
b_eq_demand <- function(q) {y = y = 8.78529 + 0.39178*(200) - 0.39178*(q)}
# b_eq_demand <- function(q) {y = 8.7853 + 0.3918*(200) - 0.3918*(q)}
# c_eq_demand <- function(q) {y = 0.321580*(230 - q) + 0.005390*(230 - q)*(230 - q) - 7.941422}
# d_eq_demand <- function(q) {y = 2.098529 - 0.059765*(300 - q) + 0.004088*(300 - q)^2}
za <- 0:250

```

```{r, out.width = c('50%', '50%'), fig.show = 'hold'}

# Use functions to graph marginal abatement cost curve

ggplot() +
#  stat_function(aes(z), color = "darkred", fun = a_eq, size = 1, show.legend = FALSE)+
  stat_function(aes(z), color = "darkblue", fun = b_eq, size = 1, show.legend = FALSE)+
  geom_point(data = raw_data, aes(x = abatement, y = mc_b))+
#  stat_function(aes(z), color = "darkorange", fun = c_eq, size = 1, show.legend = FALSE)+
#  stat_function(aes(z), color = "darkgreen", fun = d_eq, size = 1, show.legend = FALSE)+
  scale_y_continuous(limits = c(0, 400),
                     expand = c(0, 0))+
  scale_x_continuous(limits = c(0, 300),
                     expand = c(0, 0))+
  labs(x = "Abatement (Metric Tons)", 
       y = "Price (USD / Metric Ton)",
       title = "Marginal Abatement Cost")+
  theme_classic()

ggplot()+
  stat_function(aes(za), color = "darkred", fun = a_eq_demand, size = 1, show.legend = FALSE)+
  stat_function(aes(za), color = "darkblue", fun = b_eq_demand, size = 1, show.legend = FALSE)+
  stat_function(aes(za), color = "darkorange", fun = c_eq_demand, size = 1, show.legend = FALSE)+
  stat_function(aes(za), color = "darkgreen", fun = d_eq_demand, size = 1, show.legend = FALSE)+
  scale_y_continuous(limits = c(0, 400),
                     expand = c(0, 0))+
  scale_x_continuous(limits = c(0, 500),
                     expand = c(0, 0))+
  labs(x = "Pollution (Metric Tons)",
       y = "Price (USD / Metric Ton)",
       title = "Demand for Pollution")+
  theme_classic()

```

```{r}




```

